version: 2
jobs:
  test:
    # the primary container, where your job's commands are run
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run: virtualenv venv
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            source venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: pytest
          command: |
            source venv/bin/activate
            python -m pytest
